project_id = "borxkhboskbdngtrdpsd"

[functions.parse-menu]
verify_jwt = false

[functions.recommend-dishes]
verify_jwt = false

[functions.generate-dish-image]
verify_jwt = false

[functions.clear-menu-cache]
verify_jwt = false

[functions.clear-dish-image-cache]
verify_jwt = false